version: "3.4"
services:
     postgres:
          image: postgres
          environment:
               POSTGRES_DB: challenge
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: postgres
          ports:
               - "5432:5432"
     
     mongo:
          image: mongo
          environment:
               MONGO_INITDB_ROOT_USERNAME: root
               MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
               MONGO_INITDB_DATABASE: challenge
          
          ports: 
               - "27017:27017"
     redis:
          image: "redis:alpine"
          ports:
               - "6379:6379"
     celery:
          build: .
          command:  sh -c "celery -A miio_challenge worker -l info"
          depends_on:
               - postgres
               - redis
               - mongo
          image: app-image
          volumes: 
               - .:/code

     web:
          build: .
          command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8080"
          volumes: 
               - .:/code
          ports:
               - "8080:8080"
          depends_on:
               - postgres
               - mongo
               - redis
               - celery
          restart: on-failure
